# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Collection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, title: str=None, description: str=None, instruments: List[str]=None, targets: List[str]=None, optional_properties: Dict[str, List[str]]=None):  # noqa: E501
        """Collection - a model defined in Swagger

        :param id: The id of this Collection.  # noqa: E501
        :type id: str
        :param title: The title of this Collection.  # noqa: E501
        :type title: str
        :param description: The description of this Collection.  # noqa: E501
        :type description: str
        :param instruments: The instruments of this Collection.  # noqa: E501
        :type instruments: List[str]
        :param targets: The targets of this Collection.  # noqa: E501
        :type targets: List[str]
        :param optional_properties: The optional_properties of this Collection.  # noqa: E501
        :type optional_properties: Dict[str, List[str]]
        """
        self.swagger_types = {
            'id': str,
            'title': str,
            'description': str,
            'instruments': List[str],
            'targets': List[str],
            'optional_properties': Dict[str, List[str]]
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'instruments': 'instruments',
            'targets': 'targets',
            'optional_properties': 'optional_properties'
        }
        self._id = id
        self._title = title
        self._description = description
        self._instruments = instruments
        self._targets = targets
        self._optional_properties = optional_properties

    @classmethod
    def from_dict(cls, dikt) -> 'Collection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The collection of this Collection.  # noqa: E501
        :rtype: Collection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Collection.

        identifier lidvid of the collection  # noqa: E501

        :return: The id of this Collection.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Collection.

        identifier lidvid of the collection  # noqa: E501

        :param id: The id of this Collection.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Collection.


        :return: The title of this Collection.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Collection.


        :param title: The title of this Collection.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Collection.


        :return: The description of this Collection.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Collection.


        :param description: The description of this Collection.
        :type description: str
        """

        self._description = description

    @property
    def instruments(self) -> List[str]:
        """Gets the instruments of this Collection.

        identifier lidvid of the instrument or procedure generating the data  # noqa: E501

        :return: The instruments of this Collection.
        :rtype: List[str]
        """
        return self._instruments

    @instruments.setter
    def instruments(self, instruments: List[str]):
        """Sets the instruments of this Collection.

        identifier lidvid of the instrument or procedure generating the data  # noqa: E501

        :param instruments: The instruments of this Collection.
        :type instruments: List[str]
        """

        self._instruments = instruments

    @property
    def targets(self) -> List[str]:
        """Gets the targets of this Collection.

        identifier lidvid of the target of the observation  # noqa: E501

        :return: The targets of this Collection.
        :rtype: List[str]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[str]):
        """Sets the targets of this Collection.

        identifier lidvid of the target of the observation  # noqa: E501

        :param targets: The targets of this Collection.
        :type targets: List[str]
        """

        self._targets = targets

    @property
    def optional_properties(self) -> Dict[str, List[str]]:
        """Gets the optional_properties of this Collection.


        :return: The optional_properties of this Collection.
        :rtype: Dict[str, List[str]]
        """
        return self._optional_properties

    @optional_properties.setter
    def optional_properties(self, optional_properties: Dict[str, List[str]]):
        """Sets the optional_properties of this Collection.


        :param optional_properties: The optional_properties of this Collection.
        :type optional_properties: Dict[str, List[str]]
        """

        self._optional_properties = optional_properties
