# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.metadata import Metadata  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class Products(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: Metadata=None, data: List[Product]=None):  # noqa: E501
        """Products - a model defined in Swagger

        :param metadata: The metadata of this Products.  # noqa: E501
        :type metadata: Metadata
        :param data: The data of this Products.  # noqa: E501
        :type data: List[Product]
        """
        self.swagger_types = {
            'metadata': Metadata,
            'data': List[Product]
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'data': 'data'
        }
        self._metadata = metadata
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Products':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The products of this Products.  # noqa: E501
        :rtype: Products
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this Products.


        :return: The metadata of this Products.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this Products.


        :param metadata: The metadata of this Products.
        :type metadata: Metadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def data(self) -> List[Product]:
        """Gets the data of this Products.


        :return: The data of this Products.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this Products.


        :param data: The data of this Products.
        :type data: List[Product]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
